### ISSUE TITLE
False positive when using vim vixen

### ISSUE THREAD

**Issue by fedemp** [odacavo/enhanced-iframe-protection#2]
[vim vixen](https://github.com/ueokande/vim-vixen) creates an invisible iframe on every page to work. So suddenly every page as a potentially malicious iframe. 😞 

> Warning: Potential Security Risk Ahead
> An iframe element is displaying content from the following URL: moz-extension://fb590c18-134c-4552-a50e-d08c07ef29...
> Please ensure you trust this URL before entering any sensitive information such as passwords, emails, or credit card details.

**Comment by MalwareCube** [comment]
![image](https://user-images.githubusercontent.com/31866708/160294461-30277d1e-d6c2-4108-8179-1706b15b943b.png)

Tested with the vim vixen plugin. EIP working as intended and will detect any iframe on the DOM visible to the user or not. 

As tested, the fix for this issue would be to click "Close warning" (assuming you trust _vim _vixen) to add it to the browser's local whitelist. After doing so and browsing around (refresh any pages with the warning), this warning does not appear again even with vim vixen running.

**Comment by fedemp** [comment]
Oh! So it's added to a whitelist. I thought the `Close Warning` only meant to ignore it for this time. You are right that I haven't seen the warning any more.

**Comment by MalwareCube** [comment]
That is a thought though... Maybe that button could be more verbose / defined. Cheers and thanks!
